### ISSUE TITLE
Update core_version.h when using feature/stage

### ISSUE THREAD

**Issue by mcspr** [platformio/platform-espressif8266#101]
Arduino IDE updates core_version.h file when building to include current git revision and git-describe output as preprocessor tokens:
https://github.com/esp8266/Arduino/blob/master/cores/esp8266/core_version.h
https://github.com/esp8266/Arduino/blob/2eb5b5600a3631cdfb9ddd1150505d82e38f3406/platform.txt#L73-L79
It would be nice to be able to use them.

Note: ARDUINO_ESP8266_GIT_DESC=$(git describe --tags) will not work when running shallow clone (which is the default pio git-clone behaviour)

**Comment by ivankravets** [comment]
Thanks! :) https://github.com/esp8266/Arduino/commit/c5efb922cac979bd6d7ce257e7f337a9f8bc7552#diff-a96e736475cb79393ad72ec653311807
