### ISSUE TITLE
analogWriteFreq

### ISSUE THREAD

**Issue by thephantomphoenix** [platformio/platform-espressif8266#108]
Hi,

Apologies if I submit this incorrectly. First time.

However, I just wanted to let you know that I that there seems to be an issue with the analogWriteFreq function. I have been using this platform for the past 12 months. In one of my projects this function has been the same for about 12 months. 

I have been investgating an issue, that has been resolved by coming back from 1.8.0 to 1.73. When I put my device on an oscilloscope and measure the outbound frequency. Using version 1.8.0 regardless of the setting it will not come down below 100. My project uses 64. As I was narrowing it down I tried everything from 20 to 90, but no changes, always 100. Above 100 it is fine, you can set what ever you like.

Anyway, I have solved the issue on my end and don't need anything as such, but I just wanted to let you know.

If I can assist further with any more info, please let me know.

Thanks.

**Comment by ivankravets** [comment]
Could you reproduce this issue with the latest upstream version https://docs.platformio.org/en/latest/platforms/espressif8266.html#upstream?

**Comment by ivankravets** [comment]
Please reopen if you still need help
