### ISSUE TITLE
Generic ESP8285 Module size incorrect

### ISSUE THREAD

**Issue by SRChiP** [platformio/platform-espressif8266#111]
The "maximum_size" of 434160 bytes is incorrect for the ESP8285 chip [json](https://github.com/platformio/platform-espressif8266/blob/master/boards/esp8285.json).
The chip has 1M of data according to the [datasheet](https://www.espressif.com/sites/default/files/0a-esp8285_datasheet_en_v1.0_20160422.pdf) (page 12, section 3.1.3). The [arduino board section](https://github.com/esp8266/Arduino/blob/master/boards.txt#L566) shows the size as 761840 bytes after discounting the spiffs too. 
`esp8285.menu.eesz.1M256.upload.maximum_size=761840`

I think the value should be corrected.

**Comment by ivankravets** [comment]
Thanks!
