### ISSUE TITLE
#ifdef issues

### ISSUE THREAD

**Issue by debsahu** [platformio/platform-espressif8266#117]
I am trying to compile https://github.com/debsahu/ESP-MQTT-AWS-IoT-Core/tree/develop on PlatformIO and [Travis CI](https://travis-ci.com/debsahu/ESP-MQTT-AWS-IoT-Core/builds/97785248) shows that PIO is generating errors from a [portion of code](https://github.com/debsahu/ESP-MQTT-AWS-IoT-Core/blob/350a70effe3c0652775d1af47ab660c65b26486b/Arduino/MQTT/MQTT.ino#L113), which should be excluded as USE_PUB_SUB is defined.

This compiles on Arduino IDE without issues.

**Comment by ivankravets** [comment]
Have you resolved this issue?

**Comment by debsahu** [comment]
No, I just included both libraries. I will close this.
