### ISSUE TITLE
ESP8266 Arduino 2.5 - New Release

### ISSUE THREAD

**Issue by porkyneal** [platformio/platform-espressif8266#124]
Now that [2.5.0](https://github.com/esp8266/Arduino/releases) has been released, are we able to get a new release on platformio?

I have loved using the latest GIT for development. But now 2.5.0 is done, It is a great place to put a mark in the sand for my projects, especially for production code.

**Comment by lucasromeiro** [comment]
Hi, I'm interested too.

**Comment by Jason2866** [comment]
+1

**Comment by debsahu** [comment]
@1.9.0 please!

**Comment by sentoxo** [comment]
I'm waiting too.

**Comment by xtianpaiva** [comment]
+1

**Comment by aderusha** [comment]
Anyone have any advice for adding this manually into PIO until they officially support the 2.5.0 release?

**Comment by Jason2866** [comment]
@aderusha 
you could use my repo. I have this done to use core 2.5.0 for the project "Tasmota"
It is not restricted or crippled in any way. Feel free to use until official is released
To use add in platformio.ini the entry:
`platform                  = https://github.com/Jason2866/platform-espressif8266.git#Tasmota`

**Comment by lucasromeiro** [comment]
> @aderusha
> you could use my repo. I have this done to use core 2.5.0 for the project "Tasmota"
> It is not restricted or crippled in any way. Feel free to use until official is released
> To use add in platformio.ini the entry:
> `platform = https://github.com/Jason2866/platform-espressif8266.git#Tasmota`

nice...

**Comment by bigbuglamer** [comment]
+1

**Comment by ivankravets** [comment]
Please re-test with the latest upstream version https://docs.platformio.org/en/latest/platforms/espressif8266.html#upstream

if it works, we will release in a few next days.

Thanks!

**Comment by aderusha** [comment]
So far so good over here!  Have to change some code but that's due to changes in 2.5.0.  PIO is working as expected.

**Comment by FWdeveloper** [comment]
Unfortunately got FS flash error:

> Building SPIFFS image from ‘data’ directory to .pioenvs\esp_wroom_02\spiffs.bin
> *** [.pioenvs\esp_wroom_02\spiffs.bin] Error 148 

If I go back to `platform = espressif8266` FS image update works well.

**Comment by debsahu** [comment]
Default partition has no SPIFFs, one has to use `-Teagle.flash.4m3m.ld` as a **build_flags**

**Comment by Jason2866** [comment]
Release generates buggy code. See #128

**Comment by ivankravets** [comment]
What do you mean under “buggy code”? Does it work with Arduino IDE? Please share a test project to reproduce your issue.

**Comment by Jason2866** [comment]
Project Tasmota does fail
https://github.com/arendst/Sonoff-Tasmota

**Comment by Jason2866** [comment]
Solution for bug fix is in #128
