### ISSUE TITLE
linker script does not put .cc files into flash

### ISSUE THREAD

**Issue by hkahl** [platformio/platform-espressif8266#140]
In tools/sdk/ld/eagle.app.v6.common.ld.h files matching *.c.o and *.cpp .o are considered. The suffix ".cc" is a also pretty common for c++ files. Currently, if .cc is used somewhere, this code goes to iram by default which is quickly filled and linking fails. I suggest adding a line like this:

`*.cc.o(.literal*, .text*)`

to the linker script so that .cc file go to flash by default like .cpp files.

**Comment by ivankravets** [comment]
Please move this issue to https://github.com/esp8266/Arduino/issues
