### ISSUE TITLE
Problem in FS after updating the core

### ISSUE THREAD

**Issue by lucasromeiro** [platformio/platform-espressif8266#148]
Hello, I'm using PlatformIO in its latest version. 
I have now updated to use the Arduino 2.5.1 core to use ESP8266 12-F and now my code does not compile anymore!
Accuses error in FS.
I do not understand why. It worked before updating.
I can not find the problem.
Can someone help me?

<img width="562" alt="Captura de Tela 2019-05-15 às 09 19 37" src="https://user-images.githubusercontent.com/2086543/57796059-d6063a00-771d-11e9-941c-7f5258f312b5.png">
<img width="1069" alt="Captura de Tela 2019-05-15 às 09 20 33" src="https://user-images.githubusercontent.com/2086543/57796060-d69ed080-771d-11e9-9d12-b1ad31d3c6da.png">

Thank you

**Comment by lucasromeiro** [comment]
core 2.4.2 work fine:
platform = espressif8266@1.8.0


core 2.5.1 don't work:
platform = espressif8266


why??

**Comment by ivankravets** [comment]
> Unification of SPIFFS and SD, into single compatible FS, File, and Dir objects

See https://github.com/esp8266/Arduino/pull/5525

@earlephilhower do you have any migrating guide?

**Comment by earlephilhower** [comment]
There is no migration.  They are compatible AFAIK and per many other users and the original SD.h examples, even.

**Comment by ivankravets** [comment]
@lucasromeiro could you share a simple project to reproduce this issue?

**Comment by lucasromeiro** [comment]
> @lucasromeiro could you share a simple project to reproduce this issue?

Sure!

#include "Arduino.h"
#include <ESP8266WiFi.h>
#include <FS.h>          //Biblioteca responsável por criar o Sistema de manipulação de arquivos


void setup() {
  SPIFFS.begin(); //Inicializa sistema de arquivos
}

void loop() {
  
  File carregaArquivos = SPIFFS.open("/log.txt", "a");
  char charState = '1';
  carregaArquivos.write(charState);
  carregaArquivos.close();
}

<img width="1075" alt="Captura de Tela 2019-05-15 às 15 26 03" src="https://user-images.githubusercontent.com/2086543/57799616-d60a3800-7725-11e9-87f1-76ecf7dbd8f7.png">

**Comment by earlephilhower** [comment]
fs::write takes a pointer and length, or a c-string, or a String, not a char.

**Comment by lucasromeiro** [comment]
> fs::write takes a pointer and length, or a c-string, or a String, not a char.

If I use String it also does not work!
String charState = "1";

**Comment by lucasromeiro** [comment]
I do not understand why this worked in the previous version and now it does not work.

**Comment by earlephilhower** [comment]
Mybad, that is not part of the function signatures.

::write is different than ::print.  Maybe you meant to use ::print instead?

**Comment by earlephilhower** [comment]
Actually, I think I see the issue.

FS::File never had a File::write(char) method, but it did have a File::write(uint8_t) method.  Print(the superclass of File) never supported Print::write(char).

So in the old versions you were getting silent conversions of char->uint8_t (I think you'll get a warning if you go strict enough).

Now, since your call doesn't match any exactly, it is using the template which is for writing Stream children, only.

**Comment by earlephilhower** [comment]
Try the change in https://github.com/esp8266/Arduino/pull/6101 .  I'm not sure if it will break anything else, but it re-enabled the usage.

**Comment by lucasromeiro** [comment]
> Actually, I think I see the issue.
> 
> FS::File never had a File::write(char) method, but it did have a File::write(uint8_t) method. Print(the superclass of File) never supported Print::write(char).
> 
> So in the old versions you were getting silent conversions of char->uint8_t (I think you'll get a warning if you go strict enough).
> 
> Now, since your call doesn't match any exactly, it is using the template which is for writing Stream children, only.

Got it, so if I switch char to uint8_t it should work the same, right?
I'll try.

**Comment by lucasromeiro** [comment]
> Actually, I think I see the issue.
> 
> FS::File never had a File::write(char) method, but it did have a File::write(uint8_t) method. Print(the superclass of File) never supported Print::write(char).
> 
> So in the old versions you were getting silent conversions of char->uint8_t (I think you'll get a warning if you go strict enough).
> 
> Now, since your call doesn't match any exactly, it is using the template which is for writing Stream children, only.

Its work!

uint8_t charState = '1';

Thanks!
