### ISSUE TITLE
Feature Request: Arduino bugfix v.2.5.2 is released

### ISSUE THREAD

**Issue by Jason2866** [platformio/platform-espressif8266#152]
Please uppdate to 2.5.2 since it fixes the linker issue https://github.com/esp8266/Arduino/issues/6087#issuecomment-492338120

**Comment by TD-er** [comment]
Will it then be tagged as 2.1.2, or 2.2.0?    (just for me to get an idea on the version numbers for the platform versioning)

**Comment by ivankravets** [comment]
It will be 2.2.0. The path version we use for internal dev/platform bug fixes.

**Comment by ivankravets** [comment]
Please update to https://github.com/platformio/platform-espressif8266/releases/tag/v2.2.0
