### ISSUE TITLE
Add support for ESP8266 Deauther

### ISSUE THREAD

**Issue by exocode** [platformio/platform-espressif8266#169]
What kind of issue is this?

- [X] **Feature Request**.
    

Can you add this board, please?

https://github.com/LilyGO/esp8266_deauther

**PINOUT is here:** 
https://oneguyoneblog.com/2018/12/28/wemos-d1-esp-wroom-02-arduino-ide/

**Comment by ivankravets** [comment]
See settings from this repo  https://github.com/LilyGO/esp8266_deauther/raw/master/images/set%20up.png

You can use NodeMCU 1.0 board manifest. See how to configure lwIP => http://docs.platformio.org/en/latest/platforms/espressif8266.html#configuration

**Comment by exocode** [comment]
nice thanks
