### ISSUE TITLE
support littlefs for upcoming esp8266 arduino core release

### ISSUE THREAD

**Issue by liebman** [platformio/platform-espressif8266#173]
The next release of Arduino core for esp8266 will have support for more than one filesystem type.  This should be supported.

**Comment by DaleMitchell** [comment]
Bump?

**Comment by pfeerick** [comment]
Further this thread, StridingDragon has come up with a way to 'trick' PlatformIO into creating/uploading a LittleFS formatted file system for the ESP32 using an extra_script, so hopefully that makes this easier to implement formally. 

https://community.platformio.org/t/how-to-define-littlefs-partition-build-image-and-flash-it-on-esp32/11333/3

**Comment by CODeRUS** [comment]
SPIFFS is now officially deprecated:
https://github.com/esp8266/Arduino/pull/7263

**Comment by andig** [comment]
Joining the party. Not sure even how to declare the LittleFS dependency (not mentioned in https://arduino-esp8266.readthedocs.io/en/latest/filesystem.html#spiffs-and-littlefs).

**Comment by valeros** [comment]
Added in [v2.6.0](https://github.com/platformio/platform-espressif8266/releases/tag/v2.6.0)

**Comment by jbasiago** [comment]
What was the fix here?  When I look at configuring options on my project, I do not see the option board_build.filesystem even though I've loaded version 2.6.0 of the Expressif 8266 platform.  Does this fix eliminate the need for any additional outside scripts of do I still have to fool around with python to build the .bin file for the filesystem.  As far as I can tell, this fix has done nothing for me.  I'm using PlatformIO on CLion.  Thanks for any help.

**Comment by CODeRUS** [comment]
@jbasiago check https://docs.platformio.org/en/latest/platforms/espressif8266.html#using-filesystem

**Comment by jbasiago** [comment]
The issue I was having was I had not noticed the Uploadfs target in the PlatformIO build configurations in Clion.  Small details get you every time.  Once I selected this target, it all worked as described.  Thanks for the help.

**Comment by drzony** [comment]
@45gfg9 
Make sure that:
1. `board_build.filesystem = littlefs` is in correct place (either under `[env]` or `[env:myboard]`)
2. Esp8226 platform is updated to the latest version (PIO Home->Libraries->Updates)
3. Make sure Arduino core is the latest (this should update with 2. unless you have some overrides such as `framework = xxx`),

**Comment by 45gfg9** [comment]
Thanks!
I was using 2.5.3 version of framework. As I upgrade to 2.6.0 it worked.
