### ISSUE TITLE
ESp8266 Arduino V2.6.0

### ISSUE THREAD

**Issue by mars000** [platformio/platform-espressif8266#181]
I noticed this version just released on GitHub.
Just for my understanding does PlatformIO automatically pick this up as an updated within the PlatformIO GUI in VSC or do I need to wait for someone to publish a PlatformIO file of sorts ?

**Comment by Jason2866** [comment]
See #180

**Comment by Niek** [comment]
Also: https://github.com/platformio/platform-espressif8266/issues/167

**Comment by Niek** [comment]
Thanks @valeros, are you going to release a version on GitHub as well?

**Comment by valeros** [comment]
If there are no critical issues, it'll be released within a few days. As for now you can try the upstream vesion:
```
[env:upstream_develop]
platform = https://github.com/platformio/platform-espressif8266.git
board = ...
```

**Comment by dirkmueller** [comment]
It looks like tool-esptoolpy is still old, it should be 1.20800.0, with other words it needs to include https://github.com/espressif/esptool/releases/tag/v2.8

**Comment by valeros** [comment]
Do you experience any issues with the current `tool-esptoolpy`?

**Comment by dirkmueller** [comment]
@valeros not yet, however this is not matching the official release.. when you download https://github.com/esp8266/Arduino/releases/download/2.6.1/esp8266-2.6.1.zip

and do

```
$ grep __version__ tools/esptool/esptool.py
__version__ = "2.8"
```


you can see that it has 2.8, while platformio installs 2.6:

```
grep __version__ ~/.platformio/packages//tool-esptoolpy/esptool.py 
__version__ = "2.6"
```
