### ISSUE TITLE
`#include <ESP8266WiFi.h>` in library results in "No such file or directory"

### ISSUE THREAD

**Issue by jfktrey** [platformio/platform-espressif8266#19]
I'm running platformio 3.2.1 on OS X.

When choosing the nodemcuv2 board and attempting to include the ESP8266WiFi.h header file in a file in the `lib/` directory, I consistently get "ESP8266WiFi.h: No such file or directory".

This is alleviated by including the ESP8266WiFi.h header file in a file in the `src/` directory, but it seems like it should be able to work regardless.

**Comment by ybizeul** [comment]
Not sure it matters, do you use

    #include "ESP8266WiFi.h"

or

    #include <ESP8266WiFi.h>

**Comment by ivankravets** [comment]
Please reopen if you still need help
