### ISSUE TITLE
Board request: ESP-12F 160MHz

### ISSUE THREAD

**Issue by cregganna** [platformio/platform-espressif8266#195]
Hi,

Can I request that a new board is added.

Documentation is here: http://wiki.ai-thinker.com/_media/esp8266/a014ps01.pdf

It seems to be similar to the ESP-12E but claims to be clocked at 160Mhz rather than 80MHz.

I have therefore just duplicated esp12e.json and changed the f_cpu to 160000000L and am able to flash new sketches OK.

If you have a sketch you would like me to run on the board to inspect its characteristics then let me know.

Many Thanks,
Anthony

**Comment by valeros** [comment]
Hi @cregganna ! There is no need to add a new board, you can use `esp12e` board in you `platformio.ini`, just add the following line:
```
[env:esp12e]
platform = espressif8266
board = esp12e
framework = arduino

board_build.f_cpu = 160000000L
```
