### ISSUE TITLE
ESP8266WiFi has missing requirement in current platform-espressif8266 packages

### ISSUE THREAD

**Issue by ybizeul** [platformio/platform-espressif8266#20]
`tools` directory out of sync with package `ESP8266WiFi` in framework-arduinoespressif8266`.

When trying to use `ESP8266WiFi.h` it complains about missing `WPS_CB_ST_UNK` that is supposed to be declared in `tools/sdk/include/user_interface.h`.

The problem seems like the platform definition is :
```
    "framework-arduinoespressif8266": {
      "type": "framework",
      "optional": true,
      "version": "~1.20300.1"
    },
```

But it would require https://github.com/platformio/framework-arduinoespressif8266/commit/db5e20f23770e1be307348633dc497f689493996, or 1.204 ? Not sure since when that framework has been packaged, but at the time that constant has been added, there was no package.json, that might explain it.

Anyway, fetching master fixes the issue but it took me a while to figure out what was wrong

**Comment by ivankravets** [comment]
2.4.0 is out and will be released with PIO soon
