### ISSUE TITLE
esp8266_exception_decoder is not available in device monitor filters (pio core 4.3.1)

### ISSUE THREAD

**Issue by zaxari4** [platformio/platform-espressif8266#202]
<pre><font color="#8AE234"><b>zx@zxpc</b></font>:<font color="#729FCF"><b>~</b></font>$ pio --version
PlatformIO, version 4.3.1
<font color="#8AE234"><b>zx@zxpc</b></font>:<font color="#729FCF"><b>~</b></font>$ pio device monitor --filter esp8266_exception_decoder
--- Available filters and text transformations: colorize, debug, default, direct, hexlify, log2file, nocontrol, printable, send_on_enter, time
--- More details at http://bit.ly/pio-monitor-filters
<font color="#CC0000">Error: &apos;esp8266_exception_decoder&apos;</font>
<font color="#8AE234"><b>zx@zxpc</b></font>:<font color="#729FCF"><b>~</b></font>$ 
</pre>

**Comment by ivankravets** [comment]
You need upstream version of this dev-platform https://docs.platformio.org/en/latest/platforms/espressif8266.html#upstream

The final release is planend for the next week.
