### ISSUE TITLE
ArduinoOTA password not working

### ISSUE THREAD

**Issue by mklimishyn** [platformio/platform-espressif8266#205]
I was setting up a sketch from Arduino to work in platformIO for the first time and couldn't get upload_flags auth option to work.
My platformio.ini settings:
[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino

monitor_speed = 115200
upload_protocol = espota
upload_port = 192.168.0.100
upload_flags =
--auth=abcd

And I get an error:
20:50:23 [INFO]: Sending invitation to: 192.168.0.100
Authenticating...FAIL
20:50:23 [ERROR]: Authentication Failed
*** [upload] Error 1

From what I gather my syntax is correct. And any changes result in a warning that my auth parameter is being ignored. This all, of course, works completely fine without the password. I don't think it's an issue on my end. Yes, I made sure passwords match ;)

This all works fine in Arduino with hashed and plain text passwords.

I am using the following versions:
Espressif 8266 - 2.4.0
PlatformIO - Core 4.3.1 Home 3.1.1
Python - 2.7.14

**Comment by valeros** [comment]
Hi @mklimishyn ! You need to place `--auth=abcd` flag on the same line with `upload_flags` or use the tab key to indent if you want to place it on another line:
```
upload_flags = --auth=abcd
```
or
```
upload_flags =
    --auth=abcd
```

Feel free to reopen the issue if you still need any help.
