### ISSUE TITLE
[OTA] Issues with XMC flash based devices 

### ISSUE THREAD

**Issue by ashthespy** [platformio/platform-espressif8266#209]
There is an issue with OTA in 2.7.0 for devices such as the ESP-12F. After some head scratching I came across https://github.com/esp8266/Arduino/issues/7267.
Is it possible to revert to 2.6.3 or patch it?

**Comment by valeros** [comment]
Hi @ashthespy ! You can roll back to the previous version of the platform:
```
platform = espressif8266@2.4.0
framework = ...
board = ...
```

**Comment by ashthespy** [comment]
@valeros FYI, tested the patched `eboot.efl` from https://github.com/esp8266/Arduino/pull/7277 and it solves my issue. So keep an eye out of a `2.7.1` release soon and until then will use the staging version..
