### ISSUE TITLE
Builder script hardcoding upload address

### ISSUE THREAD

**Issue by streamliner18** [platformio/platform-espressif8266#22]
When trying to compile a native project without the use of Arduino framework BUT with the preconfigured loader script `esp8266.flash.4m1m.ld`, the uploaded application crashed. Later, it was determined that this loader script, processed normally when Arduino framework is in place (where irom0 code is loaded AND uploaded to flash address 0x40201010), was mistakenly uploaded to 0x40240000 with the builder.

This behavior caused inability for ESP8266 to boot from the expected address (0x01010), because the actual program was located at 0x40000.

builder/main.py, lines 299-308:

```
     UPLOADERFLAGS=[
            "-vv",
            "-cd", "$UPLOAD_RESETMETHOD",
            "-cb", "$UPLOAD_SPEED",
            "-cp", '"$UPLOAD_PORT"',
            "-ca", "0x00000",
            "-cf", "${SOURCES[0]}",
            "-ca", "0x40000",
            "-cf", "${SOURCES[1]}"
        ],
```

It seems like the builder assumes `eagle.app.v6.ld` in use (default setting for bare metal ESP8266), which indeed maps from0_0_seg at 0x40000. However, the "eagle" loaders packed with the toolchain has no support for 4MB flash memory.

Could anyone inspire me on how to fix such a problem?

**Comment by ivankravets** [comment]
You can override `UPLOADERFLAGS` with http://docs.platformio.org/en/latest/projectconf/advanced_scripting.html

**Comment by ivankravets** [comment]
Please reopen if you still need help
