### ISSUE TITLE
Please update ESP8266 Arduino framework soon

### ISSUE THREAD

**Issue by huming2207** [platformio/platform-espressif8266#23]
Hello there,

Please upgrade ESP8266 Arduino framework mirror soon, as the main upstream project repo (https://github.com/esp8266/Arduino) has fixed some bugs, updated some SDK APIs and it's useful for developments.

If you are not convenient to update, could you please tell me how to create my own mirror/fork so that I can use the newest code. Thanks.

Thanks and Regards,
Jackson

**Comment by huming2207** [comment]
Update:

I've directly downloaded the arduino framework and patched into ``/.platformio/packages/framework-arduinoespressif8266``, but there are quite a lot of linking issues when linking the ``firmware.elf``.

**Comment by ivankravets** [comment]
See http://docs.platformio.org/en/latest/platforms/espressif8266.html#using-arduino-framework-with-staging-version

**Comment by huming2207** [comment]
Just checked, it works, updated and compiled successfully. Thanks mate.
