### ISSUE TITLE
SparkFun L6470 AutoDriver_ID1300 not compiling

### ISSUE THREAD

**Issue by deladriere** [platformio/platform-espressif8266#24]
works fine for Arduino uno but with the Espressif 
`[env:esp12e]
platform = espressif8266
board = esp12e
framework = arduino`
It gives  `.piolibdeps/SparkFun L6470 AutoDriver_ID1300/src/SparkFunAutoDriverSupport.cpp:323:40: error: no matching function for call to
 'SPIClass::transfer(byte [(((sizetype)(((ssizetype)AutoDriver::_numBoards) + -1)) + 1)], int&)'`

**Comment by ivankravets** [comment]
Please report issue to https://github.com/sparkfun/SparkFun_AutoDriver_Arduino_Library
