### ISSUE TITLE
Google Cloud Build :- Error: Detected unknown package 'espressif8266' 

### ISSUE THREAD

**Issue by ben700** [platformio/platform-espressif8266#247]
[log.txt](https://github.com/platformio/platform-espressif8266/files/6339728/log.txt)

Build ends with

PlatformManager: Installing espressif8266
Error: Detected unknown package 'espressif8266'
ERROR
ERROR: build step 0 "sglahn/platformio-core:3.6.0" failed: step exited with non-zero status: 1

**Comment by valeros** [comment]
Hi @ben700 ! I'm not sure this problem has something to do with the `espressif8266` platform itself, you'd better ask the maintainer of the `sglahn/platformio-core` image.

**Comment by ben700** [comment]
Can you update with a fix

Fix was to change Python container on Google Cloud Build

like

steps:
- name: python
entrypoint: bash
args:
- '-c'
- |
pip install --upgrade platformio
pio run
dir: .

**Comment by valeros** [comment]
It might be a good idea to submit a PR to the repository where that docker image is maintained.

**Comment by ben700** [comment]
Google Cloud Support sent me toward you

**Comment by valeros** [comment]
Probably you need this repo https://github.com/sglahn/docker-platformio-core
