### ISSUE TITLE
Question: How do we find out which version of the frameworks are in this package?

### ISSUE THREAD

**Issue by adjavaherian** [platformio/platform-espressif8266#25]
How do we find out which version of the frameworks are in this package?  It looks like framework-arduinoespressif8266 and sdk-esp8266 are a little behind, no?

**Comment by ivankravets** [comment]
Do you mean this?
![screen shot 2017-03-04 at 19 03 15](https://cloud.githubusercontent.com/assets/1760209/23580590/417d7840-010d-11e7-9491-60c96ffba424.png)

**Comment by adjavaherian** [comment]
yeah, sorry.  total newb.  where do I find that panel?

**Comment by ivankravets** [comment]
PlatformIO IDE > Menu > PlatformIO > Home > Switch to PlatformIO IDE 2.0
