### ISSUE TITLE
Update to Arduino Core 3.0.2

### ISSUE THREAD

**Issue by mcspr** [platformio/platform-espressif8266#255]
New version has been released https://github.com/esp8266/Arduino/releases/tag/3.0.2

**Comment by valeros** [comment]
Updated, please retest using the upstream version of the platform:
```ini
[env:nodemcuv2]
platform = https://github.com/platformio/platform-espressif8266.git
framework = arduino
board = nodemcuv2
```

**Comment by mcspr** [comment]
It should also include toolchain bump to resolve inttypes.h issue, can't build the mcve from the linked issue
https://github.com/esp8266/Arduino/issues/8220
https://github.com/esp8266/Arduino/pull/8222

**Comment by valeros** [comment]
Thanks, toolchain packages have been updated as well, please run `pio platform update espressif8266` in your terminal.

**Comment by mcspr** [comment]
it works, thanks!

**Comment by mcspr** [comment]
@valeros should this be tagged for platform release?
