### ISSUE TITLE
Wrong PWM resolution

### ISSUE THREAD

**Issue by FernandoGarcia** [platformio/platform-espressif8266#271]
Hi!

In the versions above 2.6.3 the `analogWrite` function works with 8 bit resolution instead 10 bit.

Using the code below you will get 3.3 V instead 1.61 V on output.

```cpp
#include "Arduino.h"

const int LED_PIN = D7;
const int PWM_VALUE = 500;

void setup()
{
  pinMode(LED_PIN, OUTPUT);
  analogWrite(LED_PIN, PWM_VALUE);
}

void loop()
{
}
```
Here some pics showing the problem.

Code:

![230code](https://user-images.githubusercontent.com/2778501/159564660-6f8fded5-3341-478e-b38a-27beb535317b.jpeg)

Platformio.ini using v3.2.0:

![320ini](https://user-images.githubusercontent.com/2778501/159564771-5297f3aa-ff59-40f9-b116-f8e59ab50af9.jpeg)

Oscilloscope measurements:

![320osc](https://user-images.githubusercontent.com/2778501/159564926-1fda4337-974c-46c8-8b7e-af7e4f311df5.jpeg)

Platformio.ini using v2.6.3

![263ini](https://user-images.githubusercontent.com/2778501/159565097-1e216654-2545-4225-9d7f-8278b30393b0.jpeg)

Oscilloscope measurements:

![263osc](https://user-images.githubusercontent.com/2778501/159565194-85afecdb-0bbe-4584-ab0c-59cd7870a5d1.jpeg)

Best regards.

**Comment by mcspr** [comment]
See https://github.com/esp8266/Arduino/pull/7456 and https://github.com/esp8266/Arduino/pull/2895
Notice that this repo is for PlatformIO-specific build tools, Arduino Core related issues and it's development are at https://github.com/esp8266/Arduino

**Comment by FernandoGarcia** [comment]
Thanks you very much for the info.
Sorry by post the issue in wrong place.
