### ISSUE TITLE
no target for erase flash

### ISSUE THREAD

**Issue by atsju** [platformio/platform-espressif8266#276]
In some cases it's needed to have a full flash erase target.
Could you update the platform to have erase target like [there is for ESP32 ](https://docs.platformio.org/en/latest/platforms/espressif32.html#erase-flash)

Question has been raised in #210 but closed immediately and I do not come to same conclusion concerning erase at upload. Fir me the flash is not fully erased at upload, but only the sections being programmed after.

**Comment by valeros** [comment]
Hi @atsju, the "erase" target has been available since v2.0, you can use it via `pio run -t erase` .
