### ISSUE TITLE
Update Arduino Core to 3.1.0

### ISSUE THREAD

**Issue by thedanbob** [platformio/platform-espressif8266#290]
New version has been released: https://github.com/esp8266/Arduino/releases/tag/3.1.0

**Comment by mcspr** [comment]
Note that we also need toolchain-xtensa version bump to June 2022 one to update libc and fix an annoying gcc bug related to pointers. Plus, a couple of qol patches included
https://github.com/earlephilhower/esp-quick-toolchain/releases
(rest of the tools havent changed as far as I can see, just gcc)

https://registry.platformio.org/tools/platformio/toolchain-xtensa latest version is still for the 3.0.2
