### ISSUE TITLE
Board Lifely Agrumino Lemon unknow

### ISSUE THREAD

**Issue by Bighoneypot** [platformio/platform-espressif8266#295]
Dear, there is a problem with board Agrumino Lemon board, board unknow, impossible to use with platformio VSC.

![image](https://user-images.githubusercontent.com/35570068/225284171-f7500d81-a154-4f4f-934a-4cecbeac709d.png)

![image](https://user-images.githubusercontent.com/35570068/225284769-f59ab04d-c0a4-48c1-bdc1-c93e932b7d5e.png)

**Comment by valeros** [comment]
Hi @Bighoneypot ! You need to update the development platform. Please run `pio pkg update -g -p espressif8266` in the IDE terminal.
