### ISSUE TITLE
The board is not supported although it is listed as such

### ISSUE THREAD

**Issue by me21** [platformio/platform-espressif8266#35]
The board **esp01_1m** is not supported by framework Simba, although it is listed in supported boards at http://docs.platformio.org/en/latest/frameworks/simba.html#espressif.
Here's the **platformio.ini** file:

> ; PlatformIO Project Configuration File
> ;
> ;   Build options: build flags, source filter
> ;   Upload options: custom upload port, speed and extra flags
> ;   Library options: dependencies, extra library storages
> ;   Advanced options: extra scripting
> ;
> ; Please visit documentation for the other options and examples
> ; http://docs.platformio.org/page/projectconf.html
> 
> [env:esp01_1m]
> platform = espressif8266
> board = esp01_1m
> framework = simba
> upload_resetmethod = ck

The error during build is:

> ValueError: BOARD esp01_1m is not supported by Simba.:
> File "C:\.pioidepenv\lib\site-packages\platformio\builder\main.py", line 147:
> env.SConscript("$BUILD_SCRIPT")
> File "C:\.platformio\packages\tool-scons\script\..\engine\SCons\Script\SConscript.py", line 541:
> return _SConscript(self.fs, *files, **subst_kw)
> File "C:\.platformio\packages\tool-scons\script\..\engine\SCons\Script\SConscript.py", line 250:
> exec _file_ in call_stack[-1].globals
> File "C:\.platformio\platforms\espressif8266\builder\main.py", line 347:
> target_elf = env.BuildProgram()
> File "C:\.platformio\packages\tool-scons\script\..\engine\SCons\Environment.py", line 224:
> return self.method(*nargs, **kwargs)
> File "C:\.pioidepenv\lib\site-packages\platformio\builder\tools\platformio.py", line 56:
> env.BuildFrameworks(env.get("PIOFRAMEWORK"))
> File "C:\.platformio\packages\tool-scons\script\..\engine\SCons\Environment.py", line 224:
> return self.method(*nargs, **kwargs)
> File "C:\.pioidepenv\lib\site-packages\platformio\builder\tools\platformio.py", line 258:
> SConscript(env.GetFrameworkScript(f))
> File "C:\.platformio\packages\tool-scons\script\..\engine\SCons\Script\SConscript.py", line 604:
> return method(*args, **kw)
> File "C:\.platformio\packages\tool-scons\script\..\engine\SCons\Script\SConscript.py", line 541:
> return _SConscript(self.fs, *files, **subst_kw)
> File "C:\.platformio\packages\tool-scons\script\..\engine\SCons\Script\SConscript.py", line 250:
> exec _file_ in call_stack[-1].globals
> File "C:\.platformio\platforms\espressif8266\builder\frameworks\simba.py", line 58:
> [env.subst(join("$PLATFORMFW_DIR", "make", "platformio.sconscript"))])
> File "C:\.platformio\packages\tool-scons\script\..\engine\SCons\Script\SConscript.py", line 604:
> return method(*args, **kw)
> File "C:\.platformio\packages\tool-scons\script\..\engine\SCons\Script\SConscript.py", line 541:
> return _SConscript(self.fs, *files, **subst_kw)
> File "C:\.platformio\packages\tool-scons\script\..\engine\SCons\Script\SConscript.py", line 250:
> exec _file_ in call_stack[-1].globals
> File "C:\.platformio\packages\framework-simba\make\platformio.sconscript", line 3838:
> raise ValueError("BOARD {} is not supported by Simba.".format(board))
>  [ERROR] Took 1.84 seconds

**Comment by ivankravets** [comment]
You can use `board = esp01` and change http://docs.platformio.org/en/latest/platforms/espressif8266.html#custom-flash-size
