### ISSUE TITLE
board esp12e  doesn't support esp8266-rtos-sdk framework

### ISSUE THREAD

**Issue by petrusz1** [platformio/platform-espressif8266#41]
Got an error when triyng to compile the example provided in the rtos SDK.

--- message: ---

Error: This board doesn't support esp8266-rtos-sdk framework!

========================== [ERROR] Took 0.77 seconds ==========================

--- file: platformio.ini: ---
[env:esp012]
platform = espressif8266
board = esp12e
framework = esp8266-rtos-sdk

**Comment by StasiukDanylo** [comment]
Got a similar problem!+++

**Comment by ivankravets** [comment]
PlatformIO IDE > Home > Platforms > Updates

**Comment by ivankravets** [comment]
Please update dev/platform.
