### ISSUE TITLE
Update to esp8266 arduino core 2.4.0-rc1?

### ISSUE THREAD

**Issue by tuxedo0801** [platformio/platform-espressif8266#42]
Hi,

I'm using the esp8266 arduino core with platform.io (having 1.3.1 installed), but my implementation requires a feature that is just available with the new 2.4.0-rc1 version... see: https://github.com/esp8266/Arduino/releases

How do I get this with platform.io?

br,
Alex

**Comment by ivankravets** [comment]
See http://docs.platformio.org/en/latest/platforms/espressif8266.html#using-arduino-framework-with-staging-version
