### ISSUE TITLE
PackageManager: Installing tool-mkspiffs @ ~1.200.0 Error: Could not find a version that satisfies the requirement '~1.200.0' for your system 'windows_amd64'

### ISSUE THREAD

**Issue by dawidcieszynski** [platformio/platform-espressif8266#53]
After this commit https://github.com/platformio/platform-espressif8266/commit/bfd2397e1e34d23a43968020b028f215bfc1349b I cannot build software for nodemcuv2 using feature/stage.

Got this error:

> PackageManager: Installing tool-mkspiffs @ ~1.200.0
> Error: Could not find a version that satisfies the requirement '~1.200.0' for your system 'windows_amd64'
> 

I can handle this temporary by set platform to one commit before in platformio.ini:
```
platform = https://github.com/platformio/platform-espressif8266.git#3c7d5ab5ce959adb50e859aab485b3928082a0da
```

**Comment by ivankravets** [comment]
Thanks! Fixed
