### ISSUE TITLE
Unable to switch between esp8266 stable and development

### ISSUE THREAD

**Issue by tripish** [platformio/platform-espressif8266#59]
Commit [90e6b67e6750ca55de3ef61c08d99d8689419f9d](https://github.com/platformio/platform-espressif8266/commit/90e6b67e6750ca55de3ef61c08d99d8689419f9d) from @ivankravets removed the esp8266_stage specifier to be used in platform.ini, so now I have no way of switching between the stable and development esp8266 core without uinstalling and reinstalling the entire espressif8266 framework.

Is there a new mechanism for specifying between different versions of the same platform in the platform.ini?

**Comment by ivankravets** [comment]
http://docs.platformio.org/en/latest/platforms/espressif8266.html#using-arduino-framework-with-staging-version
