### ISSUE TITLE
Error with espressif8266_stage after running pio update

### ISSUE THREAD

**Issue by chessweb01** [platformio/platform-espressif8266#60]
I just ran `pio update` in Visual Studio Code with platformio. Now I get the following error when I open the IDE:

PlatformIO: IntelliSense Index failed: Error: Detected unknown package 'espressif8266_stage'

I have verified that espressif8266_stage is installed correctly by running `platformio platform install https://github.com/platformio/platform-espressif8266.git#feature/stage`, so that is not the problem.

When I try to build a project using the espressif8266_stage platform I get 

PlatformManager: Installing espressif8266_stage
Error: Detected unknown package 'espressif8266_stage'
The terminal process terminated with exit code: 1

in the console. What is going on?

**Comment by ivankravets** [comment]
Please update http://docs.platformio.org/en/latest/platforms/espressif8266.html#using-arduino-framework-with-staging-version
