### ISSUE TITLE
Please add support for selecting lwip2 library

### ISSUE THREAD

**Issue by Redferne** [platformio/platform-espressif8266#65]
How can we build using lwip2 without the need to manually edit esp8266-nonos-sdk.py

**Comment by sanderv32** [comment]
@Redferne lwip2 is not included in the esp8266-nonos-sdk of Espressif at the moment. Just use the library options in the `platformio.ini` file instead of modifying the `esp8266-nonos-sdk.py` file.

**Comment by Redferne** [comment]
Care to provide a working example of compiling with lwip2 and platformio.ini?  I was unsuccessful in my attempts.

**Comment by sanderv32** [comment]
I can try it out like you did, but it should not be part of esp8266-nonos-sdk until Espressif includes it. Rather see it as an separate module for plaformio.

**Comment by Redferne** [comment]
Still no support for selecting lwip2 with options? Wasn't one of the ideas behind PlatformIO to create an IDE to allow advanced usage and overcome some of the limitations in the Arduino IDE?

**Comment by sanderv32** [comment]
@Redferne Still no support as it's compiling correctly. Can't say the idea behind PlatformIO is advanced usage but @ivankravets can comment on this. Furthermore you can ofcourse contributing getting this working and create a PR. I can only speak for myself, but my spare time is limited and I have to divide it between multiple opensource projects and lwip2 is not high on my list at the moment.

**Comment by Redferne** [comment]
Yes. There's a lot of options available for ESP8266 in Arduino IDE. Debug settings etc. PlatformIO is great since it's very portable, but it is severely lacking documentation/features for advanced usage. For example, how can we override the linked core libraries/include paths in platformio.ini?

**Comment by ivankravets** [comment]
> how can we override the linked core libraries/include paths in platformio.ini?

Could you point me to the place which you do you want to override?

**Comment by Redferne** [comment]
For example in platformio-build.py. To be able to build with lwip2, you need to manually edit this file and replace lwip with lwip2 in the CPPPATH includes and replace lwip_gcc with lwip2 in LIBS. This is not very user friendly and needs to be done every single time the framework is updated. It would be really helpful if there is a way to do this using extra_script or something. But basically it comes down to that we want all options available in boards.txt should be readily available in the platformio.ini

**Comment by ivankravets** [comment]
Do you mean this? 

- https://github.com/esp8266/Arduino/blob/master/boards.txt#L265:L279

**Comment by ivankravets** [comment]
See http://docs.platformio.org/en/latest/platforms/espressif8266.html#lwip-variant

Please note that you need an upstream version of dev/platform http://docs.platformio.org/en/latest/platforms/espressif8266.html#stable-and-upstream-versions

The final release is planned on Monday.
