### ISSUE TITLE
Where does toolchain-xtensa come from?

### ISSUE THREAD

**Issue by lobradov** [platformio/platform-espressif8266#70]
I see PlatformIO pulls the toolchain from one of the repositories (dl.bintray.com, dl.platformio.org and others), but wonder how they got there.
I'm looking to see if there's updated toolchain - current one doesn't quite work on arm32v7 nor on arm64v8.

**Comment by ivankravets** [comment]
We use these https://github.com/esp8266/Arduino/blob/master/package/package_esp8266com_index.template.json#L167
