### ISSUE TITLE
Please add support to 4m2m LD Script

### ISSUE THREAD

**Issue by capedra** [platformio/platform-espressif8266#75]
@ivankravets 
Hello, could you please add support to 4m2m LD script for ESP boards? Could you please implement that for us?

According to the following links, it's possible to do that:
https://github.com/esp8266/Arduino/issues/3226
http://www.esp8266.com/viewtopic.php?f=32&t=14639

Thanks!!

**Comment by ivankravets** [comment]
Please make PR to https://github.com/esp8266/Arduino as @igrr requested here https://github.com/esp8266/Arduino/issues/3226#issuecomment-300469745

**Comment by capedra** [comment]
@ivankravets @igrr
I don't know how to do it. It's too complicated. 😐
Could you please help me out and open it? I think it will be helpful for people who wants to use OTA and SPIFFS at the same time.
Best Regards!

**Comment by bigbuglamer** [comment]
it's working for me with recent versions. Maybe issue can be closed?

**Comment by ivankravets** [comment]
Thansk!
