### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by leobel96** [platformio/platform-espressif8266#78]
I'm trying to compile the "NMEAsimple.ino" example from https://github.com/SlashDevin/NeoGPS with platformio in VSCode for NodeMCU board but I'm getting a lot of:
error: 'constexpr' needed for in-class initialization of static data member 'const float
Compiling it with Arduino IDE returns no error so, I think, it's a PlatformIO compiler error.

**Comment by ivankravets** [comment]
@valeros do you have any ideas?

**Comment by leobel96** [comment]
Maybe this one can help: https://stackoverflow.com/questions/9141950/initializing-const-member-within-class-declaration-in-c

**Comment by leobel96** [comment]
@ivankravets no solution yet?

**Comment by valeros** [comment]
Hi @leobel96 !
As a workaround, could you please try to add the next line to your `platformio.ini`
```
build_flags = -D ARDUINO=10803
```

**Comment by leobel96** [comment]
@valeros Thank you!! Now it compiles!! What is this? Should I always include that line in platformio.ini file?

**Comment by ivankravets** [comment]
Is fixed in upcoming release
