### ISSUE TITLE
change CONT_STACKSIZE

### ISSUE THREAD

**Issue by mamama1** [platformio/platform-espressif8266#81]
For one of my projects i NEED to increase the CONT_STACKSIZE in cores/esp8266/cont.h.

what is the correct way to do this? edit C:\Users\<user>\.platformio\packages\framework-arduinoespressif8266\cores\esp8266\cont.h, clean and recompile?

Is there a "cleaner" method? Should we make this configurable from platformio.ini?

**Comment by ivankravets** [comment]
* http://docs.platformio.org/en/latest/projectconf/section_env_build.html#build-flags

```
build_flags = -D CONT_STACKSIZE=999999999999
```
