### ISSUE TITLE
Auto calculate sketch size correctly 

### ISSUE THREAD

**Issue by sticilface** [platformio/platform-espressif8266#86]
```
DATA:    [====      ]  44.2% (used 36232 bytes from 81920 bytes)
PROGRAM: [=         ]  10.7% (used 450796 bytes from 4194304 bytes)
```
I'm assuming that the 4194304 comes from linker or something, however, it is misleading as the max sketch size is 1Mb (so on the 4Mb module 1Mb sketch + 3Mb for SPIFFS). However, I believe this decreases to 512K with OTA as it needs space for both bins at once so it is 512 + 512 + 3Mb. The Arduino environment env doesn't get this right either.. see below
```
Sketch uses 412828 bytes (39%) of program storage space. Maximum is 1044464 bytes.
```

issue previously mentioned here
https://github.com/platformio/platform-espressif8266/issues/26#issuecomment-397350851

**Comment by ivankravets** [comment]
Please re-test with upstream version http://docs.platformio.org/en/latest/platforms/espressif8266.html#upstream
