### ISSUE TITLE
Use esp8266/Arduino

### ISSUE THREAD

**Issue by antiFetzen** [platformio/platform-espressif8266#89]
Hello,

i want to make an HTTPS WebServer on my project. I doesn't found in the espressif repo.

Is there any way to use the repo from https://github.com/esp8266/Arduino there i found the needed libs

Thanks for help!

Update:
I added to platformio.ini
`lib_deps = https://github.com/esp8266/Arduino.git`

the lib was installed successfully but i get the following error message by compiling:
`/home/fetzen/Arduino/projects/baseDroid/src/main.ino:4:30: fatal error: WiFiServerSecure.h: No such file or directory`

Does somebody has any idea?

**Comment by ivankravets** [comment]
https://community.platformio.org/
