### ISSUE TITLE
Plan for releasing core 2.4.2?

### ISSUE THREAD

**Issue by Frogmore42** [platformio/platform-espressif8266#93]
I know that I can use the latest git version.  It would be really nice if there was a similar/easy way to use any of the released versions from https://github.com/esp8266/Arduino/releases

2.4.2 was released 5 days ago.  It looks like it took about a month for 2.4.1 to make it to a platformio release, based on: https://github.com/platformio/platform-espressif8266/issues/76

 Should I expect something similar for 2.4.2?

**Comment by ivankravets** [comment]
We will release it soon. Does 2.4.2 work well for you?

**Comment by Frogmore42** [comment]
I haven't tried it yet, but I have heard it is much better for some stability issues that are in 2.4.1.  Using it from the Arduino environment is possible, but that environment is much less nice for complex projects.
