### ISSUE TITLE
Builds broken on 1.8.0

### ISSUE THREAD

**Issue by readmodifywrite** [platformio/platform-espressif8266#96]
1.7.0 working great.
Mac OS X 10.13.6.

I've tried deleting and reinstalling the entire toolchain, to no effect.

Error output:
Compiling .pioenvs/esp12e/FrameworkArduino/cont.S.o
/Users/jeremy/.platformio/packages/framework-arduinoespressif8266/tools/sdk/libc/xtensa-lx106-elf/include/machine/_default_types.h: Assembler messages:
/Users/jeremy/.platformio/packages/framework-arduinoespressif8266/tools/sdk/libc/xtensa-lx106-elf/include/machine/_default_types.h:17: Error: unknown opcode or format name 'typedef'
/Users/jeremy/.platformio/packages/framework-arduinoespressif8266/tools/sdk/libc/xtensa-lx106-elf/include/machine/_default_types.h:18: Error: unknown opcode or format name 'typedef'
/Users/jeremy/.platformio/packages/framework-arduinoespressif8266/tools/sdk/libc/xtensa-lx106-elf/include/machine/_default_types.h:21: Error: unknown opcode or format name 'typedef'
/Users/jeremy/.platformio/packages/framework-arduinoespressif8266/tools/sdk/libc/xtensa-lx106-elf/include/machine/_default_types.h:22: Error: unknown opcode or format name 'typedef'
/Users/jeremy/.platformio/packages/framework-arduinoespressif8266/tools/sdk/libc/xtensa-lx106-elf/include/machine/_default_types.h:25: Error: unknown opcode or format name 'typedef'

There's actually quite a bit more output, but it's all the same error.  stdint.h is also affected.

Any ideas?

**Comment by dalbert2** [comment]
It builds OK for me on 1.8.0

**Comment by readmodifywrite** [comment]
Are you on a Mac?

Sorry, but that just isn't really helpful with no context at all....

**Comment by ivankravets** [comment]
Could you provide a simple project to reproduce this issue?

**Comment by ivankravets** [comment]
Please reopen if you still need help
